services:
  - type: web
    plan: free
    name: Darkthon
    env: python
    repo: https://github.com/source440/Darkthon
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 main.py
    region: frankfurt
    envVars:
      - key: ALIVE_NAME
        sync: false
      - key: API_HASH
        sync: false
      - key: APP_ID
        sync: false
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TZ
        value: Asia/Amman
      - key: PYTHON_VERSION
        value: 3.10.9
